# Generated by Django 6.0.3 on 2026-04-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marts', '0002_remove_order_image_remove_order_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
